[package]
name = "kelly"
version = "0.1.0"
edition = "2021"

[dependencies]
bip39 = "2.1.0"
bitcoin = "0.32.5"
miniscript = { version = "12.3.0", features = ["compiler"] }
reqwest = "0.12.10"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
